"""
Shared SQLAlchemy MetaData with deterministic naming conventions.

Alembic and all persistence mappings must use this `metadata` instance so
autogenerated migration names stay stable across environments.
"""

from __future__ import annotations

from sqlalchemy import MetaData

# Explicit naming conventions → deterministic Alembic constraint names.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)
